from .client import *
from .absence import *
from .attachments import *
from .changes import *
from .event import *
from .homework import *
from .komens import *
from .marks import *
from .models import *
from .subject import *
from .timetable import *
